### PR TITLE
Upgrade Docker Compose to 1.23.0 version

### PR DESCRIPTION
**Pull request by targs08**
Upgrade Docker Compose to 1.23.version

### CODE REVIEW

**Review by tyranron — CHANGES_REQUESTED** [review]
@targs08 everything is OK, but FCM is required.

**Comment by targs08** [comment]
@tyranron
FCM 
```
Upgrade Docker Compose to 1.23.0 version (#17)
```

**Comment by tyranron** [comment]
@targs08 do no hesitate to look at `git log` for commit messages

```
Upgrade Docker Compose CLI to 1.23.0 version (#17)
```

**Review by tyranron — APPROVED** [review]

**Comment by tyranron** [comment]
@targs08 now use `Squash and merge` Github button below for merging.

After that, do no forget to create a [new release](https://github.com/instrumentisto/gitlab-builder-docker-image/releases/new).

**Pull request merged**
