### PR TITLE
Upgrade composer 1.22.0 version

### PR DESCRIPTION
**Pull request by alnikyur**

### CODE REVIEW

**Comment by alnikyur** [comment]
@tyranron Something wrong with curl upload files, but local test are passing ok.

**Comment by tyranron** [comment]
@alnikyur just restart CI build until OK.

FCM?

**Comment by alnikyur** [comment]
@tyranron This is third restart :)
FCM
```
Upgrade Docker Compose CLI to 1.22.0 version
```

**Comment by tyranron** [comment]
@alnikyur 

```
Upgrade Docker Compose CLI to 1.22.0 version (#13)
```

**Review by tyranron — APPROVED** [review]

**Pull request merged**
