### PR TITLE
Add docker-compose

### PR DESCRIPTION
**Pull request by romandrahan**

### CODE REVIEW

**Review by tyranron — CHANGES_REQUESTED** [review]
Let's remove `pip` and all it's caches/data after `docker-compose` is installed.

They are not required when using image, but increase image size.

**Review by tyranron — APPROVED** [review]
Nice

**Comment by romandrahan** [comment]
@tyranron, `docker-compose` stopped working after uninstalling `py-pip`. Solving...

**Review by tyranron — APPROVED** [review]
👍

**Pull request merged**
