### PR TITLE
Update kubectl to v1.10.5

### PR DESCRIPTION
**Pull request by alnikyur**

### CODE REVIEW

**Comment by tyranron** [comment]
@alnikyur __DO NOT__ forget about FCM (final commit message).

**Review by tyranron — CHANGES_REQUESTED** [review]
@alnikyur __DO NOT__ forget about FCM (final commit message).

**Comment by alnikyur** [comment]
@tyranron Can i merge this PR?

**Comment by alnikyur** [comment]
@tyranron FCM  
```
Upgrade Kubernetes CLI to 1.10.5 version (#10)
```

**Review by tyranron — APPROVED** [review]

**Pull request merged**
